# Generated by Django 4.1.5 on 2023-08-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to=''),
        ),
    ]
